import {useState} from "react";

import { ChatProvider, useChat } from './contexts/ChatContext';
import { Input } from './components/Input';
import { ChatHistory } from './components/ChatHistory';
import { ChatsList } from './components/ChatsList';
import './App.css';
//import new_chat_white from './images/wand_stars_white.png';
import new_chat_black from './images/wand_stars_black.png';
import main_logo from './images/yin-yang.png';


function AppContent() {
    const {
        activeChatId,
        addChat,
        getActiveChat,
    } = useChat();

    const [sidebarOpen, setSidebarOpen] = useState(false);

    const handleNewChat = () => {
        addChat();
        setSidebarOpen(false);
    };

    const toggleSidebar = () => {
        setSidebarOpen(!sidebarOpen);
    };

    const closeSidebar = () => {
        setSidebarOpen(false);
    };

    const currentChat = getActiveChat();

    console.log(currentChat);
    console.log(activeChatId);

    return (
        <div className="App">
            <div
                className="sidebar-btn"
                onClick={toggleSidebar}
            >
                {sidebarOpen ? 'x' : '☰'}
            </div>

            {sidebarOpen && (
                <div className="sidebar-overlay" onClick={closeSidebar}></div>
            )}
            <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
                <div className="logo">
                    <img className="image" src={main_logo} alt={"logo"} />
                    <span className="name">Zen-AI</span>
                </div>
                <button className="new-chat-btn" onClick={handleNewChat}>
                    New chat <img src={new_chat_black} alt={"new chat"}/>
                </button>
                <ChatsList
                    onCloseSidebar={closeSidebar}
                />
            </aside>
            <main className="chat-container" onClick={() => sidebarOpen && closeSidebar()}>
                <ChatHistory
                    title = {currentChat.title}
                    messages={currentChat.messages}
                />
                <span className='info'>Generated by AI. For reference only</span>
            </main>
        </div>
    );
}

function App() {
    return (
        <ChatProvider>
            <AppContent />
        </ChatProvider>
    );
}

export default App;