// App.js
import { ChatProvider, useChat } from './contexts/ChatContext';
import { Input } from './components/Input';
import { ChatHistory } from './components/ChatHistory';
import { ChatsList } from './components/ChatsList';
import './App.css';
//import new_chat_white from './images/wand_stars_white.png';
import new_chat_black from './images/wand_stars_black.png';
import main_logo from './images/yin-yang.png';

function AppContent() {
    const {
        chats,
        activeChat,
        setActiveChat,
        addMessage,
        addChat,
        getActiveChat,
        generatedResponse,
        isLoading
    } = useChat();

    const handleSendMessage = async (message) => {
        if (!message.trim()) return;

        addMessage(activeChat, message);

        await generatedResponse(activeChat, message);
    };

    const handleNewChat = () => {
        addChat();
    };

    const currentChat = getActiveChat();

    return (
        <div className="App">
            <aside className="sidebar">
                <div className="logo">
                    <img className="image" src={main_logo} alt={"logo"} />
                    <span className="name">Zen-AI</span>
                </div>
                <button className="new-chat-btn" onClick={handleNewChat}>
                    New chat <img src={new_chat_black} alt={"new chat"}/>
                </button>
                <ChatsList
                    chats={chats}
                    activeChat={activeChat}
                    onSelectChat={setActiveChat}
                />
            </aside>
            <main className="chat-container">
                <ChatHistory messages={currentChat.messages} isLoading={isLoading} />
                <Input onSend={handleSendMessage} />
                <span className='info'>Generated by AI. For reference only</span>
            </main>
        </div>
    );
}

function App() {
    return (
        <ChatProvider>
            <AppContent />
        </ChatProvider>
    );
}

export default App;